xtensa/esp32: Add AES hardware accelerator driver
apache/incubator-nuttx pull request #2716
Opened 2021-01-19 02:29 UTC by donghengqaz

## Summary

Add AES hardware accelerator driver.

## Impact

## Testing

boards/xtensa/esp32/esp32-devkitc/configs/aes/defconfig.

2021-01-19 15:13 UTC, Ouss4 commented
@donghengqaz the defconfig supplied needs to be refreshed: `./tools/refresh.sh --silent esp32-devkitc/aes`

2021-01-20 12:30 UTC, acassis requested changes

2021-01-20 12:30 UTC, acassis commented on arch/xtensa/src/esp32/esp32_aes.c
> +      ;
This ";" inside is not necessary. You can put it after the "}" if you want, but also not necessary!

2021-01-20 12:30 UTC, acassis commented on arch/xtensa/src/esp32/esp32_aes.c
> +      printf("ESP32 AES ECB key=%d bits test: PASS\n", keybits);
Don't use printf() in the kernel

2021-01-20 12:30 UTC, acassis commented on arch/xtensa/src/esp32/esp32_aes.c
> +      printf("ESP32 AES CBC key=%d bits test: PASS\n", keybits);
Don't use printf() in the kernel

2021-01-20 12:30 UTC, acassis commented on arch/xtensa/src/esp32/esp32_aes.c
> +      printf("ESP32 AES CTR key=%d bits test: PASS\n", keybits);
Don't use printf() in the kernel

2021-01-20 12:30 UTC, acassis commented on arch/xtensa/src/esp32/esp32_aes.c
> +      printf("ESP32 AES XTS key=%d bits test: PASS\n", keybits);
Ditto

2021-01-20 12:30 UTC, acassis commented on arch/xtensa/src/esp32/esp32_aes.c
> +  printf("\nESP32 AES hardware accelerate test done.\n");
Ditto

2021-01-21 18:06 UTC, merged