stm32h7: Allow OTGHS to use internal FS PHY
apache/incubator-nuttx pull request #3522
Opened 2021-04-11 17:41 UTC by antmerlino

## Summary
Prior to this change, the OTGHS peripheral's PHYSEL bit was always left in it's default state of 0 (External ULPI). This change adds a Kconfig option to switch between having an External ULPI, or using the built-in Full-Speed PHY. 

## Impact
Users who were using the OTGHS with an external ULPI, probably no one, will have to select the STM32H7_EXTERNAL_ULPI option.

## Testing
Ran OTGHS CDCACM console using the OTGHS peripheral with the built-in FS PHY.

2021-04-11 21:59 UTC, acassis commented
@antmerlino will it work for OTS_HS1 and OTS_HS2?
I think it is important to include the information that OTGHS will work in only in FS in this case, maybe:
"No External ULPI, fallback to Full-Speed using internal OTGFS PHY"

2021-04-12 12:59 UTC, davids5 commented
> @antmerlino will it work for OTS_HS1 and OTS_HS2?

The Data Sheet says:

2× USB OTG interfaces (1FS, 1HS/FS)

The devices embed two USB OTG high-speed (up to 480 Mbit/s) device/host/OTG peripheral. OTG-HS1 supports both full-speed and high-speed operations, while OTG-HS2 supports only full-speed operations. They both integrate the transceivers for full-speed operation (12 Mbit/s). **OTG-HS1 features a UTMI low-pin interface (ULPI) for high-speed operation (480 Mbit/s). When using the USB OTG-HS1 in HS mode, an external PHY device connected to the ULPI is required.**

> "No External ULPI, fallback to Full-Speed using internal OTGFS PHY"

"No External ULPI hardware on board. OTG_HS1 is limited to Full-Speed using internal OTGFS PHY"

2021-04-12 13:07 UTC, davids5 requested changes
@antmerlino - minor wording. See if it make sense?

2021-04-12 13:07 UTC, davids5 commented on arch/arm/src/stm32h7/Kconfig
> +		Select to enable the presence of an external ULPI PHY
```suggestion
		Select to indicate the presence of an external ULPI PHY and use it.
```

2021-04-12 19:08 UTC, antmerlino commented
> 
> 
> @antmerlino will it work for OTS_HS1 and OTS_HS2?
> I think it is important to include the information that OTGHS will work only in FS in this case, maybe:
> "No External ULPI, fallback to Full-Speed using internal OTGFS PHY"

@acassis When you say "it is important to include the information..." How are you intending for this information to be presented?

1. Kconfig
2. Compile Time error
3. Run-time error

2021-04-12 19:10 UTC, antmerlino commented on arch/arm/src/stm32h7/Kconfig
> +		Select to enable the presence of an external ULPI PHY
@davids5 done.

2021-04-12 19:30 UTC, acassis commented
> > @antmerlino will it work for OTS_HS1 and OTS_HS2?
> > I think it is important to include the information that OTGHS will work only in FS in this case, maybe:
> > "No External ULPI, fallback to Full-Speed using internal OTGFS PHY"
> 
> @acassis When you say "it is important to include the information..." How are you intending for this information to be presented?
> 
>     1. Kconfig
> 
>     2. Compile Time error
> 
>     3. Run-time error

I think you found it, thank you! ;-)

2021-04-12 19:32 UTC, acassis commented
Oh no, you didn't. It was in the bool msg in the menuconfig:
"No External ULPI hardware on board. OTG_HS1 is limited to Full-Speed using internal OTGFS PHY"

2021-04-12 22:03 UTC, davids5 approved these changes
@antmerlino - Thank you

2021-04-12 22:10 UTC, davids5 commented
@antmerlino - there is now a conflict, would you please rebase and address @acassis comment in the config file. The force push,

2021-04-12 23:20 UTC, antmerlino commented
> 
> 
> @antmerlino - there is now a conflict, would you please rebase and address @acassis comment in the config file. The force push,

@davids5 Rebased and force pushed.

@acassis I've tried to address your concerns in the Kconfig help. Let me know if that covers it.

2021-04-13 01:33 UTC, acassis commented
> > @antmerlino - there is now a conflict, would you please rebase and address @acassis comment in the config file. The force push,
> 
> @davids5 Rebased and force pushed.
> 
> @acassis I've tried to address your concerns in the Kconfig help. Let me know if that covers it.

Ok! This is fine!

2021-04-13 04:21 UTC, xiaoxiang781216 approved these changes

2021-04-13 04:21 UTC, merged