Add heap & stack check to idle thread
apache/incubator-nuttx pull request #4016
Opened 2021-07-01 11:14 UTC by GUIDINGLI

## Summary

Add heap & stack check to idle thread

## Impact
idle
## Testing

2021-07-01 19:28 UTC, davids5 requested changes
See inline

2021-07-01 19:28 UTC, davids5 commented on sched/init/nx_start.c
> +          flags = enter_critical_section();
This seems like 1) it would not be power management friendly.  2) it is too draconian. This would be bad in production code.

Margin is margin and if the interrupt stack is used it is a real margin.  If there is margin we do not want a hardfault.  The would be better as separate task that can report the margin, not fault.

2021-07-02 03:48 UTC, GUIDINGLI commented on sched/init/nx_start.c
> +          flags = enter_critical_section();
Yes, you are right, so I add debug config CONFIG_STACK_USAGE_SAFE_PERCENT, default NOT open.
In the production code, this feature should be closed, but it is useful for project developing & debugging.

would be better as separate task that can report the margin 
---- Where ?  each task report its own task usage ? 
 Or create a debugging thread to only check this, then the priority is ?  I this there is no difference with IDLE thread.

Once there is stack overflow, then report or PANIC is no difference. IN the production code we will code PANIC debug.

2021-07-02 06:48 UTC, xiaoxiang781216 commented on sched/init/nx_start.c
> +          flags = enter_critical_section();
@davids5 this code path is only for deveopment, and it's guarded by CONFIG_STACK_USAGE_SAFE_PERCENT, which is in the OFF state by default. For the separate task solution, it already exist here:
https://github.com/apache/incubator-nuttx-apps/tree/master/system/stackmonitor
Since the separate task solution may report the overflow too later, the check in IDLE thread is very useful in the development phase.

2021-07-02 14:17 UTC, xiaoxiang781216 commented on sched/init/nx_start.c
> +          flags = enter_critical_section();
@davids5 what you opinion?

2021-07-02 14:57 UTC, davids5 commented on sched/init/nx_start.c
> +          flags = enter_critical_section();
Condition it be condition on DEBUG?

2021-07-02 15:12 UTC, xiaoxiang781216 commented on sched/init/nx_start.c
> +          flags = enter_critical_section();
No, by new option STACK_USAGE_SAFE_PERCENT, it's redundant to let user select both DEBUG and STACK_USAGE_SAFE_PERCENT to turn on this feature. user can disable the check by set STACK_USAGE_SAFE_PERCENT=0(the default value)

2021-07-02 15:18 UTC, davids5 commented on Kconfig
> +		Idle thread will timely check stack usage when this marco value > 0.
```suggestion
		Idle thread will timely check stack usage when this marco value > 0.
		
		N.B. This feature should not be used in production code. 
```

2021-07-02 15:19 UTC, davids5 requested changes
Please add the text

2021-07-03 16:49 UTC, GUIDINGLI commented on Kconfig
> +		Idle thread will timely check stack usage when this marco value > 0.
done, thanks

2021-07-03 16:51 UTC, davids5 approved these changes

2021-07-03 17:56 UTC, merged