fix(sensor): align for selftest interface define.
apache/incubator-nuttx pull request #4850
Opened 2021-11-18 10:03 UTC by jane2226

Align for selftest interface in struct sensor_ops_s

Signed-off-by: songnannan <songnannan@xiaomi.com>

## Summary
Align for selftest interface in struct sensor_ops_s
## Impact
nothing
## Testing
Test in my own EVB.

2021-11-18 12:44 UTC, acassis commented
Hi @jane2226 we are getting errors on HEAD of the master:
```
In file included from sensors/wtgahrs2.c:37:
sensors/wtgahrs2.c: In function 'wtgahrs2_gps_data':
Error: sensors/wtgahrs2.c:332:14: error: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
  332 |       sninfo("Time : %llu utc_time: %llu\n",
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  333 |              rtdata->gps.timestamp, rtdata->gps.time_utc);
      |              ~~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         uint64_t {aka long unsigned int}
sensors/wtgahrs2.c:332:25: note: format string is defined here
  332 |       sninfo("Time : %llu utc_time: %llu\n",
      |                      ~~~^
      |                         |
      |                         long long unsigned int
      |                      %lu
In file included from sensors/wtgahrs2.c:37:
Error: sensors/wtgahrs2.c:332:14: error: format '%llu' expects argument of type 'long long unsigned int', but argument 4 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
  332 |       sninfo("Time : %llu utc_time: %llu\n",
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  333 |              rtdata->gps.timestamp, rtdata->gps.time_utc);
      |                                     ~~~~~~~~~~~~~~~~~~~~
      |                                                |
      |                                                uint64_t {aka long unsigned int}
sensors/wtgahrs2.c:332:40: note: format string is defined here
  332 |       sninfo("Time : %llu utc_time: %llu\n",
      |                                     ~~~^
      |                                        |
      |                                        long long unsigned int
      |                                     %lu
cc1: all warnings being treated as errors
make[1]: *** [Makefile:110: wtgahrs2.o] Error 1
make[1]: Target 'libdrivers.a' not remade because of errors.
make: *** [tools/LibTargets.mk:89: drivers/libdrivers.a] Error 2
sensortest.c: In function 'print_gps':
Error: sensortest.c:169:29: error: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
  169 |   printf("%s: timestamp: %llu time_utc: %llu latitude: %f longitude: %f "
      |                          ~~~^
      |                             |
      |                             long long unsigned int
      |                          %lu
......
  172 |          " %u\n", name, event->timestamp, event->time_utc, event->latitude,
      |                         ~~~~~~~~~~~~~~~~
      |                              |
      |                              uint64_t {aka long unsigned int}
Error: sensortest.c:169:44: error: format '%llu' expects argument of type 'long long unsigned int', but argument 4 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
  169 |   printf("%s: timestamp: %llu time_utc: %llu latitude: %f longitude: %f "
      |                                         ~~~^
      |                                            |
      |                                            long long unsigned int
      |                                         %lu
......
  172 |          " %u\n", name, event->timestamp, event->time_utc, event->latitude,
      |                                           ~~~~~~~~~~~~~~~
      |                                                |
      |                                                uint64_t {aka long unsigned int}
sensortest.c: In function 'print_gps_satellite':
Error: sensortest.c:183:29: error: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
  183 |   printf("%s: timestamp: %llu count: %u satellites: %u", name,
      |                          ~~~^
      |                             |
      |                             long long unsigned int
      |                          %lu
  184 |          event->timestamp, event->count, event->satellites);
      |          ~~~~~~~~~~~~~~~~    
      |               |
      |               uint64_t {aka long unsigned int}
cc1: all warnings being treated as errors
make[3]: *** [/github/workspace/sources/apps/Application.mk:192: sensortest.c.github.workspace.sources.apps.testing.sensortest.o] Error 1
make[3]: Target 'all' not remade because of errors.
make[2]: *** [Makefile:42: /github/workspace/sources/apps/testing/sensortest_all] Error 2
make[2]: Target '/github/workspace/sources/apps/libapps.a' not remade because of errors.
make[1]: *** [Makefile:36: all] Error 2
make: *** [tools/LibTargets.mk:210: /github/workspace/sources/apps/libapps.a] Error 2
make: Target 'all' not remade because of errors.
/github/workspace/sources/nuttx/tools/testbuild.sh: line 252: /github/workspace/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
  Normalize sim/sensor
```

2021-11-18 12:49 UTC, xiaoxiang781216 commented
@acassis the fix is here https://github.com/apache/incubator-nuttx/pull/4846

2021-11-18 18:39 UTC, xiaoxiang781216 approved these changes

2021-11-18 18:58 UTC, Ouss4 approved these changes
LGTM!

2021-11-18 18:59 UTC, Ouss4 requested changes

2021-11-18 18:59 UTC, Ouss4 commented on include/nuttx/sensors/ioctl.h
> + * Argument:     A argument of calibration value for sensor.
```suggestion
 * Argument:     Calibration value for the sensor.
```

2021-11-18 18:59 UTC, Ouss4 commented on include/nuttx/sensors/ioctl.h
> + * Note:         If setting calibvalue is failed, return errno, otherwise,
```suggestion
 * Note:         If setting calibvalue failed, return errno, otherwise,
```

2021-11-18 19:02 UTC, Ouss4 commented on include/nuttx/sensors/ioctl.h
> + *               return OK.
```suggestion
 * Note:         If setting calibvalue failed, a negated errno value is return,
 *               otherwise, OK is returned.
```

2021-11-19 01:30 UTC, xiaoxiang781216 commented on include/nuttx/sensors/ioctl.h
> + *               return OK.
Done.

2021-11-19 01:31 UTC, xiaoxiang781216 commented on include/nuttx/sensors/ioctl.h
> + * Argument:     A argument of calibration value for sensor.
Done.

2021-11-19 10:07 UTC, xiaoxiang781216 commented
@Ouss4 could you take a look?

2021-11-19 10:22 UTC, Ouss4 approved these changes
LGTM!

2021-11-19 10:55 UTC, merged

2021-11-19 12:15 UTC, jane2226 commented
> LGTM!

Thanks a lot!

2021-11-19 12:15 UTC, jane2226 commented
> @Ouss4 could you take a look?

Thanks a lot!