fs/epoll: support EPOLL full events
apache/incubator-nuttx pull request #5937
Opened 2022-04-01 06:09 UTC by Donny9

## Summary
fs/epoll: support EPOLL full events

Signed-off-by: Jiuzhu Dong <dongjiuzhu1@xiaomi.com>
## Impact
support EPOLLHUP,EPOLLRDHUP,EPOLLONESHOT...
## Testing
local test

2022-04-01 08:36 UTC, xiaoxiang781216 commented on fs/vfs/Kconfig
> +config EPOLL_FULLEVENTS
let's change events type instead add config option

2022-04-01 09:51 UTC, Donny9 commented on fs/vfs/Kconfig
> +config EPOLL_FULLEVENTS
Okay, Done

2022-04-01 10:02 UTC, pkarashchenko approved these changes

2022-04-01 10:08 UTC, xiaoxiang781216 approved these changes

2022-04-01 12:13 UTC, pkarashchenko requested changes

2022-04-01 12:13 UTC, pkarashchenko commented on arch/arm/src/cxd56xx/cxd56_geofence.c
> +          gnssinfo("Report events: %02" PRIx32 "\n", fds->revents);
```suggestion
          gnssinfo("Report events: %08" PRIx32 "\n", fds->revents);
```
here and in other places

2022-04-01 13:04 UTC, xiaoxiang781216 approved these changes

2022-04-01 14:17 UTC, pkarashchenko approved these changes

2022-04-02 16:25 UTC, xiaoxiang781216 commented
@Donny9 please fix the printf warning.

2022-04-07 04:14 UTC, merged

2022-04-07 07:03 UTC, pkarashchenko commented
@xiaoxiang781216 mainline CI fails with
```
In file included from sensors/sensor.c:33:
sensors/sensor.c: In function 'sensor_pollnotify':
Error: sensors/sensor.c:170:22: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'pollevent_t' {aka 'long unsigned int'} [-Werror=format=]
  170 |               sninfo("Report events: %02x\n", fd->revents);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~
      |                                                 |
      |                                                 pollevent_t {aka long unsigned int}
sensors/sensor.c:170:41: note: format string is defined here
  170 |               sninfo("Report events: %02x\n", fd->revents);
      |                                      ~~~^
      |                                         |
      |                                         unsigned int
      |                                      %02lx
cc1: all warnings being treated as errors
make[1]: *** [Makefile:91: sensor.o] Error 1
```

2022-04-07 07:36 UTC, yamt commented
> fs/epoll: change type of eventset from uint8_t to uint32_t to support EPOLLONESHOT and so on.

can you explain a bit?
does linux support these EPOLL flags for poll(2)?

2022-04-07 08:29 UTC, xiaoxiang781216 commented
> > fs/epoll: change type of eventset from uint8_t to uint32_t to support EPOLLONESHOT and so on.
> 
> can you explain a bit? does linux support these EPOLL flags for poll(2)?

https://man7.org/linux/man-pages/man2/epoll_ctl.2.html
```
EPOLLONESHOT (since Linux 2.6.2)
              Requests one-shot notification for the associated file
              descriptor.  This means that after an event notified for
              the file descriptor by [epoll_wait(2)](https://man7.org/linux/man-pages/man2/epoll_wait.2.html), the file descriptor
              is disabled in the interest list and no other events will
              be reported by the epoll interface.  The user must call
              epoll_ctl() with EPOLL_CTL_MOD to rearm the file
              descriptor with a new event mask.

              This flag is an input flag for the event.events field when
              calling epoll_ctl(); it is never returned by
              [epoll_wait(2)](https://man7.org/linux/man-pages/man2/epoll_wait.2.html).
```