Added RP2040 Boards:  Adafruit KB2040 and Adafruit Feather RP2040
apache/incubator-nuttx pull request #6528
Opened 2022-06-27 03:18 UTC by curuvar

## Summary

Added Board definition files for Adafruit KB2040 and Adafruit Feather RP2040.

Added NeoPixel driver that supports the upper-half/lower-half model for RP2040.
This was necessary as the existing ws2812 driver only outputs to SPI pins and those don't map to the neopixels on the new boards. The implementation uses the PIO hardware.  I'm planning to update the RP2040 neopixel driver to use DMA so other code can run while the pixels are being update.

## Impact

Should not impact existing code.

## Testing

Created builds with new code and tested driver with single and multiple neopixel chains.

2022-06-27 04:04 UTC, xiaoxiang781216 approved these changes

2022-06-27 04:12 UTC, btashton commented
Seems like we should combine the two drivers, even if that means making some changes to the existing one. neopixel is just a marketing name for the same chip. 

I wrote the original one and would be happy to see the upperhalf change to support other lower half drivers. I did something similar in a private branch to use the SAMD timers (the spi controller on that chip won't drive them).

2022-06-27 04:13 UTC, btashton requested changes
See comment above

2022-06-27 04:53 UTC, curuvar commented
I agree that it would be better to use the more generic name.   I didn't try to work with the existing ws2812 as it is so closely wedded to SPI and I cannot use SPI to drive the on-board pixels on the Adafruit RP2040 boards.

Also, I choose a slightly different model for mine.  Instead of the driver buffering the pixel data I just let the user write whatever string of pixels needed.  That seemed more straightforward, but I can see the utility in having a the driver maintain a single buffer that different apps could update.

Anyone care to suggest a new name for mine (ws2812b ?) so the two can exist in parallel so as not to break existing code.

2022-06-27 14:52 UTC, acassis commented
@curuvar currently there is only a board using @btashton original WS2812 driver, so I think you can modify his driver to include your improvement. Also because there are many RBG matrixes powered by WS2812 on Aliexpress and others sites it could be interested to create a driver to use WS2812 matrix like an ordinary LCD display, like I the MAX7219 driver drivers/lcd/max7219.c see the video here: https://www.youtube.com/watch?v=Xpr1VTV5iKw&t=250s

2022-06-27 15:05 UTC, acassis commented on boards/arm/rp2040/adafruit-feather/src/rp2040_appinit.c
> +#endif
Please consider "#include <sys/types.h>" instead of doing it.

2022-06-27 15:05 UTC, acassis commented on boards/arm/rp2040/adafruit-kb2040/src/rp2040_appinit.c
> +#endif
ditto

2022-06-27 15:05 UTC, acassis commented
Nice work @curuvar

2022-06-27 18:00 UTC, btashton commented
Yeah there is at least one other person that modified it a bit to support a non in-tree board but I fully support making changes to improve this even if it does mean changing the interface slightly. I think that is better than having two implementations to support.

2022-06-28 17:50 UTC, curuvar commented
I combined my code for the ws2812 driver with the existing driver.  This is still somewhat of a work in progress.  I want to improve the code that actually outputs the bits to the pixel chain so that it runs in the background instead of hogging the CPU.



I'm fixing the code check issues (I thought I ran that scan before committing).

2022-06-29 23:09 UTC, curuvar commented
Can someone explain to me what the Check/check status means?  stm32_wlan_firmware.c isn't a file I did anything to.

2022-06-30 20:19 UTC, acassis approved these changes

2022-06-30 20:20 UTC, acassis commented
@btashton could you please review and remove the Change Request?

2022-07-01 05:13 UTC, btashton approved these changes
Thanks for making these changes!

2022-07-01 05:13 UTC, merged

2022-08-12 15:56 UTC, diegoherranz commented
Why has CONFIG_WS2812_FREQUENCY been scaled by 10?

https://github.com/apache/incubator-nuttx/blame/master/drivers/leds/ws2812.c#L81 and similar changes.

It breaks existing out-of-tree board configs. And I'm not even sure why we would want to have scaled down.
Is it a mistake? Are we OK to revert that bit?

Thanks!

2022-08-13 16:07 UTC, diegoherranz commented
After reading the code again, I think it was an attempt to express always the bit frequency directly. But, for SPI, it wouldn't be divided by 10 either, but by 8. Given that only a few SPI frequencies can be obtained in many MCUs, I find it clearer to define the actual SPI frequency when in SPI mode.

I've submitted https://github.com/apache/incubator-nuttx/pull/6849 to revert that behaviour for the SPI mode and explained it in detail in Kconfig.

I hope that's OK. Thanks!