add heapcheck(memcheck) flag
apache/incubator-nuttx pull request #6724
Opened 2022-07-28 07:34 UTC by pengxiang-hao

## Summary
1. repalced  `TCB_FLAG_MEM_CHECK` by `TCB_FLAG_HEAPCHECK`
2.  add heapcheck flag

1 for open heapcheck, 0 for close
 `echo 1 > /proc/xxx/heapcheck`
 `echo 0 > /proc/xxx/heapcheck`

## Impact
Using of `TCB_FLAG_MEM_CHECK` may need to be replaced with `TCB_FLAG_HEAPCHECK`.

## Testing
Vela CI

2022-07-28 08:16 UTC, xiaoxiang781216 commented on fs/procfs/fs_procfsproc.c
> +  &g_heapcheck,    /* Task heap check flag */
should guard by #ifdef CONFIG_DEBUG_MM

2022-07-28 08:16 UTC, xiaoxiang781216 commented on fs/procfs/fs_procfsproc.c
> +static const struct proc_node_s g_heapcheck =
should guard by #ifdef CONFIG_DEBUG_MM

2022-07-28 08:16 UTC, xiaoxiang781216 commented on fs/procfs/fs_procfsproc.c
> +  &g_heapcheck,    /* Task heap check flag */
ditto

2022-07-28 08:16 UTC, xiaoxiang781216 commented on fs/procfs/fs_procfsproc.c
> +static ssize_t proc_heapcheck(FAR struct proc_file_s *procfile,
should guard by #ifdef CONFIG_DEBUG_MM

2022-07-28 08:16 UTC, xiaoxiang781216 commented on fs/procfs/fs_procfsproc.c
> +static ssize_t proc_heapcheck(FAR struct proc_file_s *procfile,
ditto

2022-07-28 09:08 UTC, davids5 requested changes
@pengxiang-hao - 

The title and Summary, Impact, Testing do not document what this PR does. I makes is sound like you renamed and added a flag. Please document the changes herein and answer the questions **Why** it is needed and **What** does and **How**  Please do this by editing the title and Summary, Impact, Testing above.

2022-07-28 09:08 UTC, davids5 commented on fs/procfs/fs_procfsproc.c
> +  PROC_HEAP_CHECK,                    /* Tash heap check flag */
```suggestion
  PROC_HEAP_CHECK,                    /* Task heap check flag */
```

2022-07-28 09:26 UTC, davids5 commented
@xiaoxiang781216 - I think we cross posted. There have been no changes since I reviewed the PR and asked for changes.

2022-07-28 09:52 UTC, xiaoxiang781216 commented
> @xiaoxiang781216 - I think we cross posted. There have been no changes since I reviewed the PR and asked for changes.

I think "The title and Summary, Impact, Testing" is updated, but the code isn't. @pengxiang-hao please update the code too.

2022-07-28 09:55 UTC, davids5 commented
> > @xiaoxiang781216 - I think we cross posted. There have been no changes since I reviewed the PR and asked for changes.
> 
> I think "The title and Summary, Impact, Testing" is updated, but the code isn't. @pengxiang-hao please update the code too.

GH logs the edits. I do not see any sine I posted. Do you?

2022-07-31 13:18 UTC, xiaoxiang781216 approved these changes

2022-07-31 13:18 UTC, xiaoxiang781216 commented
@davids5 please review the update.

2022-08-02 02:46 UTC, merged