Support the stack size and address for posix_spawn and kernel mode
apache/incubator-nuttx pull request #7364
Opened 2022-10-20 03:37 UTC by xiaoxiang781216

## Summary

- sched/spawn: Support task_spawnattr_[set|get]stacksize in kernel mode 
- sched/spawn: Support task_spawnattr_[set|get]stackaddr for posix_spawn

## Impact
New function

## Testing
Pass CI

2022-10-20 19:54 UTC, pkarashchenko approved these changes

2022-10-20 19:54 UTC, pkarashchenko commented on binfmt/binfmt_exec.c
> +      if (attr->stackaddr)
```suggestion
      if (attr->stackaddr != NULL)
```

2022-10-20 19:54 UTC, pkarashchenko commented
Please rebase

2022-10-20 20:00 UTC, xiaoxiang781216 commented
Done

2022-10-20 23:55 UTC, masayuki2009 commented
@xiaoxiang781216 
I noticed that 'hello' ELF application does not work.

```
NuttShell (NSH) NuttX-3.6.1
nsh> uname -a
NuttX  3.6.1 cc61cd3b65 Oct 21 2022 08:43:42 arm spresense
nsh> ps
  PID GROUP CPU PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK   USED  FILLED COMMAND
    0     0   0   0 FIFO     Kthread N-- Assigned           00000000 001000 000456  45.6%  CPU0 IDLE
    1     1   1   0 FIFO     Kthread N-- Running            00000000 001000 000228  22.8%  CPU1 IDLE
    2     2 --- 224 RR       Kthread --- Waiting  Semaphore 00000000 001992 000660  33.1%  hpwork 0x2d0597f4
    3     3 ---  60 RR       Kthread --- Waiting  Semaphore 00000000 001992 000300  15.0%  lpwork 0x2d05980c
    5     5 --- 200 RR       Task    --- Waiting  MQ empty  00000000 000976 000472  48.3%  cxd56_pm_task
    6     6   0 100 RR       Task    --- Running            00000000 003024 001500  49.6%  spresense_main
nsh> ls -l /mnt/sd0/bin
/mnt/sd0/bin:
 -rw-rw-rw-    3716 hello
nsh> help
help usage:  help [-v] [<cmd>]

  .          cmp        exec       ls         mv         set        uname      
  [          dirname    exit       md5        nfsmount   sleep      umount     
  ?          date       false      mkdir      printf     source     unset      
  basename   dd         free       mkfatfs    ps         test       uptime     
  break      df         help       mkfifo     pwd        telnetd    usleep     
  cat        dmesg      hexdump    mkrd       reboot     time       wget       
  cd         echo       ifconfig   mksmartfs  rm         true       xd         
  cp         env        kill       mount      rmdir      truncate   

Builtin Apps:
  nxhello     ntpcstatus  udpblaster  getprime    nsh         msdis       
  ftpc        nxrecorder  sh          tcpclient   smp         nxplayer    
  webserver   gs2200m     nx          ftpd_stop   
  tcpserver   ntpcstart   ntpcstop    taskset     nxlines     
  renew       ostest      ftpd_start  nxdemo      msconn      
nsh> hello

```

2022-10-21 08:58 UTC, xiaoxiang781216 commented
I will take a look tonight or tomorrow, thanks.

2022-10-23 06:52 UTC, xiaoxiang781216 commented
@masayuki2009 I am trying to repro on sim:loadable, but the result looks good:
```
./nuttx 

NuttShell (NSH) NuttX-10.4.0
nsh> /system/bin/hello
Hello, World!!
```
Does it work before my change in your environment?

2022-10-23 07:30 UTC, masayuki2009 commented
>Does it work before my change in your environment?

@xiaoxiang781216 
Yes. The latest upstream works.

2022-10-24 23:36 UTC, masayuki2009 requested changes
```
NuttShell (NSH) NuttX-3.6.1
nsh> uname -a
[    2.321496] exec_spawn: ERROR: Failed to load program 'uname': -2
NuttX  3.6.1 8d2e0b7740-dirty Oct 25 2022 08:33:22 arm spresense
nsh> hello
[    8.502035] load_absmodule: Loading /mnt/sd0/bin/hello
[    8.504293] elf_loadbinary: Loading file: /mnt/sd0/bin/hello
[    8.509939] elf_init: filename: /mnt/sd0/bin/hello loadinfo: 0x2d066b88
[    8.517598] elf_read: Read 52 bytes from offset 0
[    8.521474] elf_dumploadinfo: LOAD_INFO:
[    8.525106] elf_dumploadinfo:   textalloc:    00000000
[    8.530232] elf_dumploadinfo:   dataalloc:    00000000
[    8.535359] elf_dumploadinfo:   textsize:     0
[    8.539876] elf_dumploadinfo:   datasize:     0
[    8.544392] elf_dumploadinfo:   textalign:    0
[    8.548909] elf_dumploadinfo:   dataalign:    0
[    8.553425] elf_dumploadinfo:   filelen:      3716
[    8.558186] elf_dumploadinfo:   symtabidx:    0
[    8.562702] elf_dumploadinfo:   strtabidx:    0
[    8.567219] elf_dumploadinfo: ELF Header:
[    8.571217] elf_dumploadinfo:   e_ident:      7f 45 4c 46
[    8.576588] elf_dumploadinfo:   e_type:       0001
[    8.581348] elf_dumploadinfo:   e_machine:    0028
[    8.586140] elf_dumploadinfo:   e_version:    00000001
[    8.591266] elf_dumploadinfo:   e_entry:      00000001
[    8.596363] elf_dumploadinfo:   e_phoff:      0
[    8.600879] elf_dumploadinfo:   e_shoff:      2636
[    8.605670] elf_dumploadinfo:   e_flags:      05000000
[    8.610797] elf_dumploadinfo:   e_ehsize:     52
[    8.615375] elf_dumploadinfo:   e_phentsize:  0
[    8.619891] elf_dumploadinfo:   e_phnum:      0
[    8.624408] elf_dumploadinfo:   e_shentsize:  40
[    8.629016] elf_dumploadinfo:   e_shnum:      27
[    8.633624] elf_dumploadinfo:   e_shstrndx:   26
[    8.638202] elf_load: loadinfo: 0x2d066b88
[    8.642291] elf_read: Read 1080 bytes from offset 2636
[    8.648150] up_textheap_memalign: ** ret=0x2d06ce70
[    8.652270] up_textheap_memalign: ** mapped to 0xd06ce70
[    8.657580] elf_loadfile: Loaded sections:
[    8.661639] elf_read: Read 16 bytes from offset 52
[    8.666674] elf_loadfile: 1. 00000000->0d06ce70
[    8.670946] elf_read: Read 15 bytes from offset 68
[    8.675707] elf_loadfile: 3. 00000010->0d06ce80
[    8.680223] elf_read: Read 1 bytes from offset 83
[    8.684923] elf_loadfile: 4. 0000001f->2d06cea0
[    8.689409] elf_loadfile: 7. 00000020->2d06cea4
[    8.693926] elf_dumploadinfo: LOAD_INFO:
[    8.697832] elf_dumploadinfo:   textalloc:    0d06ce70
[    8.702959] elf_dumploadinfo:   dataalloc:    2d06cea0
[    8.708085] elf_dumploadinfo:   textsize:     32
[    8.712694] elf_dumploadinfo:   datasize:     4
[    8.717210] elf_dumploadinfo:   textalign:    4
[    8.721696] elf_dumploadinfo:   dataalign:    1
[    8.726213] elf_dumploadinfo:   filelen:      3716
[    8.731004] elf_dumploadinfo:   symtabidx:    0
[    8.735520] elf_dumploadinfo:   strtabidx:    0
[    8.740037] elf_dumploadinfo: ELF Header:
[    8.744004] elf_dumploadinfo:   e_ident:      7f 45 4c 46
[    8.749405] elf_dumploadinfo:   e_type:       0001
[    8.754166] elf_dumploadinfo:   e_machine:    0028
[    8.758957] elf_dumploadinfo:   e_version:    00000001
[    8.764054] elf_dumploadinfo:   e_entry:      00000001
[    8.769180] elf_dumploadinfo:   e_phoff:      0
[    8.773697] elf_dumploadinfo:   e_shoff:      2636
[    8.778488] elf_dumploadinfo:   e_flags:      05000000
[    8.783585] elf_dumploadinfo:   e_ehsize:     52
[    8.788212] elf_dumploadinfo:   e_phentsize:  0
[    8.792728] elf_dumploadinfo:   e_phnum:      0
[    8.797245] elf_dumploadinfo:   e_shentsize:  40
[    8.801853] elf_dumploadinfo:   e_shnum:      27
[    8.806430] elf_dumploadinfo:   e_shstrndx:   26
[    8.811038] elf_dumploadinfo: Sections 0:
[    8.815036] elf_dumploadinfo:   sh_name:      00000000
[    8.820163] elf_dumploadinfo:   sh_type:      00000000
[    8.825290] elf_dumploadinfo:   sh_flags:     00000000
[    8.830386] elf_dumploadinfo:   sh_addr:      00000000
[    8.835513] elf_dumploadinfo:   sh_offset:    0
[    8.840029] elf_dumploadinfo:   sh_size:      0
[    8.844546] elf_dumploadinfo:   sh_link:      0
[    8.849062] elf_dumploadinfo:   sh_info:      0
[    8.853579] elf_dumploadinfo:   sh_addralign: 0
[    8.858095] elf_dumploadinfo:   sh_entsize:   0
[    8.862612] elf_dumploadinfo: Sections 1:
[    8.866579] elf_dumploadinfo:   sh_name:      0000001f
[    8.871706] elf_dumploadinfo:   sh_type:      00000001
[    8.876833] elf_dumploadinfo:   sh_flags:     00000006
[    8.881960] elf_dumploadinfo:   sh_addr:      0d06ce70
[    8.887087] elf_dumploadinfo:   sh_offset:    52
[    8.891664] elf_dumploadinfo:   sh_size:      16
[    8.896272] elf_dumploadinfo:   sh_link:      0
[    8.900789] elf_dumploadinfo:   sh_info:      0
[    8.905305] elf_dumploadinfo:   sh_addralign: 4
[    8.909822] elf_dumploadinfo:   sh_entsize:   0
[    8.914338] elf_dumploadinfo: Sections 2:
[    8.918336] elf_dumploadinfo:   sh_name:      0000001b
[    8.923432] elf_dumploadinfo:   sh_type:      00000009
[    8.928559] elf_dumploadinfo:   sh_flags:     00000040
[    8.933686] elf_dumploadinfo:   sh_addr:      00000000
[    8.938813] elf_dumploadinfo:   sh_offset:    2036
[    8.943574] elf_dumploadinfo:   sh_size:      16
[    8.948182] elf_dumploadinfo:   sh_link:      24
[    8.952790] elf_dumploadinfo:   sh_info:      1
[    8.957306] elf_dumploadinfo:   sh_addralign: 4
[    8.961792] elf_dumploadinfo:   sh_entsize:   8
[    8.966309] elf_dumploadinfo: Sections 3:
[    8.970306] elf_dumploadinfo:   sh_name:      00000025
[    8.975433] elf_dumploadinfo:   sh_type:      00000001
[    8.980560] elf_dumploadinfo:   sh_flags:     00000032
[    8.985687] elf_dumploadinfo:   sh_addr:      0d06ce80
[    8.990783] elf_dumploadinfo:   sh_offset:    68
[    8.995391] elf_dumploadinfo:   sh_size:      15
[    9.000000] elf_dumploadinfo:   sh_link:      0
[    9.004516] elf_dumploadinfo:   sh_info:      0
[    9.009033] elf_dumploadinfo:   sh_addralign: 1
[    9.013549] elf_dumploadinfo:   sh_entsize:   1
[    9.018066] elf_dumploadinfo: Sections 4:
[    9.022033] elf_dumploadinfo:   sh_name:      0000002d
[    9.027160] elf_dumploadinfo:   sh_type:      00000001
[    9.032286] elf_dumploadinfo:   sh_flags:     00000003
[    9.037413] elf_dumploadinfo:   sh_addr:      2d06cea0
[    9.042540] elf_dumploadinfo:   sh_offset:    83
[    9.047118] elf_dumploadinfo:   sh_size:      1
[    9.051634] elf_dumploadinfo:   sh_link:      0
[    9.056151] elf_dumploadinfo:   sh_info:      0
[    9.060667] elf_dumploadinfo:   sh_addralign: 1
[    9.065184] elf_dumploadinfo:   sh_entsize:   0
[    9.069700] elf_dumploadinfo: Sections 5:
[    9.073698] elf_dumploadinfo:   sh_name:      00000033
[    9.078794] elf_dumploadinfo:   sh_type:      00000001
[    9.083921] elf_dumploadinfo:   sh_flags:     00000001
[    9.089048] elf_dumploadinfo:   sh_addr:      00000020
[    9.094175] elf_dumploadinfo:   sh_offset:    84
[    9.098783] elf_dumploadinfo:   sh_size:      0
[    9.103300] elf_dumploadinfo:   sh_link:      0
[    9.107786] elf_dumploadinfo:   sh_info:      0
[    9.112302] elf_dumploadinfo:   sh_addralign: 1
[    9.116819] elf_dumploadinfo:   sh_entsize:   0
[    9.121335] elf_dumploadinfo: Sections 6:
[    9.125333] elf_dumploadinfo:   sh_name:      0000003a
[    9.130460] elf_dumploadinfo:   sh_type:      00000001
[    9.135587] elf_dumploadinfo:   sh_flags:     00000001
[    9.140683] elf_dumploadinfo:   sh_addr:      00000020
[    9.145810] elf_dumploadinfo:   sh_offset:    84
[    9.150418] elf_dumploadinfo:   sh_size:      0
[    9.154934] elf_dumploadinfo:   sh_link:      0
[    9.159451] elf_dumploadinfo:   sh_info:      0
[    9.163967] elf_dumploadinfo:   sh_addralign: 1
[    9.168484] elf_dumploadinfo:   sh_entsize:   0
[    9.172970] elf_dumploadinfo: Sections 7:
[    9.176968] elf_dumploadinfo:   sh_name:      00000041
[    9.182094] elf_dumploadinfo:   sh_type:      00000008
[    9.187221] elf_dumploadi [...]

2022-10-25 03:39 UTC, anchao commented
@masayuki2009 Could you please verify this PR again?

2022-10-27 02:07 UTC, masayuki2009 commented
@anchao @xiaoxiang781216 
It seems that the hello app issue with `spresense:wifi` has been resolved.
However, `sabre-6qaud:knsh_smp` has the following issue.

```
+ /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-arm -semihosting -M sabrelite -m 1024 -smp 4 -kernel nuttx -nographic
ABCDGHIJKNOPQ
[    0.040000] [CPU0] up_assert: Assertion failed CPU0 at file:common/arm_createstack.c line: 91 task: CPU0 IDLE
[    0.040000] [CPU0] up_assert: Assertion failed CPU0 at file:armv7-a/arm_syscall.c line: 488 task: CPU0 IDLE
[    0.040000] [CPU0] arm_registerdump: R0: 00000000 R1: 108184a4 R2: 02020000  R3: 00000000
[    0.040000] [CPU0] arm_registerdump: R4: 108184a4 R5: 10817ab8 R6: 10817a58  FP: 1081a5f8
[    0.040000] [CPU0] arm_registerdump: R8: 1081a5f8 SB: 00000064 SL: 10817ab8 R11: 00000005
[    0.040000] [CPU0] arm_registerdump: IP: 00000009 SP: 1081a5e4 LR: 10806141  PC: 10806218
[    0.040000] [CPU0] arm_registerdump: CPSR: 6000017f
[    0.040000] [CPU0] arm_dump_stack: IRQ Stack:
[    0.040000] [CPU0] arm_dump_stack: sp:     10816020
[    0.040000] [CPU0] arm_dump_stack:   base: 10815850
[    0.040000] [CPU0] arm_dump_stack:   size: 00000800
[    0.040000] [CPU0] arm_stackdump: 10816020: 1081a49c 10817a58 fffffff8 1081a5f8 1081a5f8 10803e39 00000000 10800d75
[    0.040000] [CPU0] arm_dump_stack: User Stack:
[    0.040000] [CPU0] arm_dump_stack: sp:     1081a5e4
[    0.040000] [CPU0] arm_dump_stack:   base: 10819f18
[    0.040000] [CPU0] arm_dump_stack:   size: 000007e8
[    0.040000] [CPU0] arm_stackdump: 1081a5e0: 6000017f 10806141 1081559e 0000005b 10817b58 10806f57 10817ab8 1081ce00
[    0.040000] [CPU0] arm_stackdump: 1081a600: 00000000 00000000 10813513 10803e39 0000000c 1081275f 00000000 1081ce00
[    0.040000] [CPU0] arm_stackdump: 1081a620: 00000000 1080fed9 1081ce00 10813513 80000761 1081ce00 1081cdc0 10813513
[    0.040000] [CPU0] arm_stackdump: 1081a640: 1081cdd8 1081a6cc 10817dd4 1080c9fb 10817ab8 80000761 00000000 1081ced0
[    0.040000] [CPU0] arm_stackdump: 1081a660: 1081ced0 00000000 80200000 00000000 00000000 00000000 00000000 1081cdc0
[    0.040000] [CPU0] arm_stackdump: 1081a680: 10813513 1081a6bc 1081a6c0 1080bed9 00000000 00000000 1081a6c0 1081a6cc
[    0.040000] [CPU0] arm_stackdump: 1081a6a0: 10817ab8 10817dc4 10817ab8 10801c09 00000000 1081a6cc 00000002 00000000
[    0.040000] [CPU0] arm_stackdump: 1081a6c0: 108134d0 108134d6 00000000 10016400 00000000 10817ab8 00000004 10817dc8
[    0.040000] [CPU0] arm_stackdump: 1081a6e0: 10817db8 10801b71 18000000 08000000 80500000 00000000 00000000 00000000
[    0.040000] [CPU0] arm_dump_stack: Kernel Stack:
[    0.040000] [CPU0] arm_dump_stack: sp:     1081a5e4
[    0.040000] [CPU0] arm_dump_stack:   base: 00000000
[    0.040000] [CPU0] arm_dump_stack:   size: 00000c00
[    0.040000] [CPU0] arm_dump_stack: ERROR: Kernel Stack pointer is not within the stack
[    0.040000] [CPU0] arm_showtasks:    PID    PRI   CPU     STACK      USED   FILLED    COMMAND
[    0.040000] [CPU0] arm_showtasks:   ----   ----  ----      2048       420    20.5%    irq
[    0.040000] [CPU0] arm_dump_task:      0      0     0      2024       896    44.2%    CPU0 IDLE
[    0.040000] [CPU0] arm_dump_task:      1      0     1      2024       664    32.8%    CPU1 IDLE
[    0.040000] [CPU0] arm_dump_task:      2      0     2      2024       664    32.8%    CPU2 IDLE
[    0.040000] [CPU0] arm_dump_task:      3      0     3      2024       664    32.8%    CPU3 IDLE
```

2022-10-29 18:35 UTC, xiaoxiang781216 commented
> @anchao @xiaoxiang781216 It seems that the hello app issue with `spresense:wifi` has been resolved. However, `sabre-6qaud:knsh_smp` has the following issue.
> 
> ```
> + /home/ishikawa/opensource/QEMU/qemu-7.1/build/qemu-system-arm -semihosting -M sabrelite -m 1024 -smp 4 -kernel nuttx -nographic
> ABCDGHIJKNOPQ
> [    0.040000] [CPU0] up_assert: Assertion failed CPU0 at file:common/arm_createstack.c line: 91 task: CPU0 IDLE
> [    0.040000] [CPU0] up_assert: Assertion failed CPU0 at file:armv7-a/arm_syscall.c line: 488 task: CPU0 IDLE
> [    0.040000] [CPU0] arm_registerdump: R0: 00000000 R1: 108184a4 R2: 02020000  R3: 00000000
> [    0.040000] [CPU0] arm_registerdump: R4: 108184a4 R5: 10817ab8 R6: 10817a58  FP: 1081a5f8
> [    0.040000] [CPU0] arm_registerdump: R8: 1081a5f8 SB: 00000064 SL: 10817ab8 R11: 00000005
> [    0.040000] [CPU0] arm_registerdump: IP: 00000009 SP: 1081a5e4 LR: 10806141  PC: 10806218
> [    0.040000] [CPU0] arm_registerdump: CPSR: 6000017f
> [    0.040000] [CPU0] arm_dump_stack: IRQ Stack:
> [    0.040000] [CPU0] arm_dump_stack: sp:     10816020
> [    0.040000] [CPU0] arm_dump_stack:   base: 10815850
> [    0.040000] [CPU0] arm_dump_stack:   size: 00000800
> [    0.040000] [CPU0] arm_stackdump: 10816020: 1081a49c 10817a58 fffffff8 1081a5f8 1081a5f8 10803e39 00000000 10800d75
> [    0.040000] [CPU0] arm_dump_stack: User Stack:
> [    0.040000] [CPU0] arm_dump_stack: sp:     1081a5e4
> [    0.040000] [CPU0] arm_dump_stack:   base: 10819f18
> [    0.040000] [CPU0] arm_dump_stack:   size: 000007e8
> [    0.040000] [CPU0] arm_stackdump: 1081a5e0: 6000017f 10806141 1081559e 0000005b 10817b58 10806f57 10817ab8 1081ce00
> [    0.040000] [CPU0] arm_stackdump: 1081a600: 00000000 00000000 10813513 10803e39 0000000c 1081275f 00000000 1081ce00
> [    0.040000] [CPU0] arm_stackdump: 1081a620: 00000000 1080fed9 1081ce00 10813513 80000761 1081ce00 1081cdc0 10813513
> [    0.040000] [CPU0] arm_stackdump: 1081a640: 1081cdd8 1081a6cc 10817dd4 1080c9fb 10817ab8 80000761 00000000 1081ced0
> [    0.040000] [CPU0] arm_stackdump: 1081a660: 1081ced0 00000000 80200000 00000000 00000000 00000000 00000000 1081cdc0
> [    0.040000] [CPU0] arm_stackdump: 1081a680: 10813513 1081a6bc 1081a6c0 1080bed9 00000000 00000000 1081a6c0 1081a6cc
> [    0.040000] [CPU0] arm_stackdump: 1081a6a0: 10817ab8 10817dc4 10817ab8 10801c09 00000000 1081a6cc 00000002 00000000
> [    0.040000] [CPU0] arm_stackdump: 1081a6c0: 108134d0 108134d6 00000000 10016400 00000000 10817ab8 00000004 10817dc8
> [    0.040000] [CPU0] arm_stackdump: 1081a6e0: 10817db8 10801b71 18000000 08000000 80500000 00000000 00000000 00000000
> [    0.040000] [CPU0] arm_dump_stack: Kernel Stack:
> [    0.040000] [CPU0] arm_dump_stack: sp:     1081a5e4
> [    0.040000] [CPU0] arm_dump_stack:   base: 00000000
> [    0.040000] [CPU0] arm_dump_stack:   size: 00000c00
> [    0.040000] [CPU0] arm_dump_stack: ERROR: Kernel Stack pointer is not within the stack
> [    0.040000] [CPU0] arm_showtasks:    PID    PRI   CPU     STACK      USED   FILLED    COMMAND
> [    0.040000] [CPU0] arm_showtasks:   ----   ----  ----      2048       420    20.5%    irq
> [    0.040000] [CPU0] arm_dump_task:      0      0     0      2024       896    44.2%    CPU0 IDLE
> [    0.040000] [CPU0] arm_dump_task:      1      0     1      2024       664    32.8%    CPU1 IDLE
> [    0.040000] [CPU0] arm_dump_task:      2      0     2      2024       664    32.8%    CPU2 IDLE
> [    0.040000] [CPU0] arm_dump_task:      3      0     3      2024       664    32.8%    CPU3 IDLE
> ```

@masayuki2009 the problem is fixed. sabre-6qaud:knsh_smp should work now.

2022-10-31 03:46 UTC, masayuki2009 commented
>@masayuki2009 the problem is fixed. sabre-6qaud:knsh_smp should work now.

@xiaoxiang781216 
I confirmed that the latest PR fixes the issue.

2022-10-31 03:46 UTC, masayuki2009 approved these changes

2022-10-31 03:46 UTC, merged